### ISSUE TITLE
Router DLINK-822 get 500 return code

### ISSUE THREAD

**Issue by jingl3s** [ldotlopez/python-hnap#1]
Hi,

Thanks for refactoring the management of HNAP. I am in similar behavior and want to make some setup over my D-Link router 822.

I was able to talk to my router through some investigation with browser debug and extracting a restricted Curl command
`curl 'http://192.168.254.1/HNAP1/' -X POST -H 'Content-Type: text/xml; charset=utf-8' -H 'SOAPAction: "http://purenetworks.com/HNAP1/Login"'  --data-raw '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><Login xmlns="http://purenetworks.com/HNAP1/"><Action>request</Action><Username>Admin</Username><LoginPassword></LoginPassword><Captcha></Captcha></Login></soap:Body></soap:Envelope>'`

When I use the python requests, I have a 500 error like if I remove one of the headers

```python
method = "POST"
url = "http://192.168.254.1:80/HNAP1"
data = '<?xml version="1.0" encoding="utf-8"?><soap:Envelope   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"   xmlns:xsd="http://www.w3.org/2001/XMLSchema"   xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">  <soap:Body>   <Login xmlns="http://purenetworks.com/HNAP1/">          <Action>request</Action>\n     <Username>admin</Username>\n     <LoginPassword></LoginPassword>\n     <Captcha></Captcha>   </Login>  </soap:Body></soap:Envelope>'
headers = {
    "Content-Type": "text/xml; charset=utf-8",
    "SOAPAction": "http://purenetworks.com/HNAP1/Login",
}
TIMEOUT = 10
resp = requests.request(
    method=method, url=url, data=data, headers=headers, timeout=TIMEOUT
)
```

If you have experienced similar behavior with your devices I will appreciate some troubleshooting guides, in order to figure out the root cause. I have tried many libraries and always getting strange things and different answers.

My final objective will be to extend the router in order to permit also an integration in Home assistant to enable or disable Wifi.

Thanks

After writing this, I have investigated and was able to figure out one issue point as the :80 is not accepted by the router. There is still an issue with your calls. I will investigate and if figure out the issue I will propose a PR for the device.

**Comment by ldotlopez** [comment]
Thanks for the info.

I have made a quick test and current code works with my devices and I have my HA running with my custom integration, so... I don't know what to say...

You can try something like this piece of code and running it under ipdb step by step
```
import hnap
client = hnap.soapclient.SoapClient("router", password="123456")
print(client.authenticated)

client.authenticate()
print(client.authenticated)
print(repr(client.call("GetDeviceSettings")))
```

>  After writing this, I have investigated and was able to figure out one issue point as the :80 is not accepted by the router. There is still an issue with your calls. I will investigate and if figure out the issue I will propose a PR for the device.

Looking forward to your comments :+1:

**Comment by jingl3s** [comment]
Hi Luis,

I do not think going to push a PR for the extension I am going to perform for my need with the router as to retrieve network usages and a swtich to enable and disable Wifi.

I will also take a look at your component to manage the device from Home Assistant. It will reduce my man work on that.

**Comment by jingl3s** [comment]
PR Closed and issue resolved
Thanks Luis
